name = input("What is your name?")
age = input("How old are you?")
baseballTeam = input("What is your favorite baseball team?")
print("You are:")
print(name)
print("You are:")
print(age)
print("You like the:")
print(baseballTeam)